---
title: "p8105_hw2_mjd2283"
author: "Max"
date: "2026-10-09"
output: html_document
---

#Problem 2

```{r}
library(tidyverse)

mr_trash_df = 
  readxl::read_excel("./202610 Trash Wheel Collection Data.xlsx", sheet = "Mr. Trash Wheel", range = "A2:N742") |>
  janitor::clean_names() |>
  drop_na(dumpster) |>
  mutate(
    sports_balls = as.integer(round(sports_balls)),
    year = as.numeric(year),
    trash_wheel = "Mr Trash")

professor_trash_df =
  readxl::read_excel("./202610 Trash Wheel Collection Data.xlsx", sheet = "Professor Trash Wheel", range = "A2:M139") |>
  janitor::clean_names() |>
  drop_na(dumpster) |>
  mutate(
    plastic_bottles = as.numeric(plastic_bottles),
    trash_wheel = "Professor Trash")

gwynnda_df = 
  readxl::read_excel("./202610 Trash Wheel Collection Data.xlsx", sheet = "Gwynnda the Good Wheel of the W", range = "A2:L394") |>
  janitor::clean_names() |>
  drop_na(dumpster) |>
  mutate(trash_wheel = "Gwynnda")

combined_df =
  bind_rows(mr_trash_df, professor_trash_df, gwynnda_df) |> 
  relocate(trash_wheel)

combined_df

#went from A2 headers to N742 last row of possible data excluding the totals row
#also added the sheet option
#clean names makes it snake case

#only including dumpster rows (drop_na), mutating so that the number of sports balls is rounded
#labeling each trash wheel as different names

#years can't combine in between sheets so need to fix
#also similar issue with plastic bottles

#clarifying names
```
```{r}

total_weight_professor = 
  combined_df |>
  filter(trash_wheel == "Professor Trash") |>
  pull(weight_tons) |>
  sum(na.rm = TRUE)

print(total_weight_professor)

total_cigarette_gwynnda =
  combined_df |> 
  filter(trash_wheel == "Gwynnda", month == "June", year == "2022") |>
  pull(cigarette_butts) |>
  sum(na.rm = TRUE)
  
print(total_cigarette_gwynnda)

```

In line R code here!

#Problem 3

```{r}

library(tidyverse)

baseline_original=
  read_csv("./data_mci/MCI_baseline.csv", 
    skip = 1, na = c (".", "NA", "")) |>
    janitor::clean_names() 

baseline_df =
  baseline_original |>
  mutate(
    sex = case_match(
        sex, 
        1 ~ "male", 
        0 ~ "female"),
    sex = as.factor(sex),
    apoe4 = case_match(
      apoe4, 
        1 ~ "carrier", 
        0 ~ "non-carrier"),
    apoe4 = as.factor(apoe4)) |>
  filter(is.na(age_at_onset) | age_at_onset > current_age)

#using case match to ensure not numeric 
  
#labeled it as characters and then used as.factor to turn it to a factor

#used filter() to remove participants who do not meet stated inclusion criteria

recruited = nrow(baseline_original)
included = nrow(baseline_df)
developed_mci = 
  baseline_df |>
  filter(!is.na(age_at_onset)) |>
  pull(id) |>
  length()
mean_age = mean(baseline_df$current_age, na.rm = TRUE)

baseline_df
  
#For this question, filtered out those had NA in the age_at_onset meaning they didn't develop MCI. Used AI to help with this approach

women_apoe4 = baseline_df |>
filter(sex == "female") |>
  mutate (gene = apoe4 == "carrier") |>
  pull(gene) |>
  mean()

#finding proportion by classifying APOE4 as either True or False so 1 or 0 and then finding the mean. Used AI to help with code reasoning here

amyloid_original=
  read_csv("./data_mci/MCI_amyloid.csv",
    skip = 1, na = c (".", "NA", "")) |>
  janitor::clean_names() |>
  rename(id = study_id) 

amyloid_df =
  amyloid_original |>
  pivot_longer(baseline:time_8,
    names_to = "visit",
    values_to = "amyloid_ratio") |>
   mutate(
    visit = replace(visit, visit == "baseline", "time_0"),
    visit = factor(visit)) 

#pivot_longer to change so visits all under one column and values under another

n_baseline_only =
  baseline_df |>
  filter(!(id %in% amyloid_df$id)) |>
  pull(id) |>
  length()

n_baseline_only

n_amyloid_only =
  amyloid_original |>
  filter(!(id %in% baseline_df$id)) |>
  pull(id) |>
  length()

n_amyloid_only

#used %in% so see if the id value was in the other dataset and ! keeps only those that are not

mci_df = inner_join(baseline_df, amyloid_df, by = "id")

write_csv(mci_df, "./data_mci/mci_combined.csv")
  
mci_df



```
The remaining dataset contains id values across visits including time_0 which is baseline and then up to time_8

8 participants are labeled only in the baseline dataset
16 participants are labeled only in the amyloid dataset






